services:
  guacd:
    image: guacamole/guacd
    restart: always

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: guac
      MYSQL_USER: guac
      MYSQL_PASSWORD: guac_pw
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - ./mysql_data:/var/lib/mysql:rw
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  guacamole:
    image: guacamole/guacamole
    restart: always
    environment:
      GUACD_HOSTNAME: guacd
      WEBAPP_CONTEXT: ROOT
      TOTP_ENABLED: true
      MYSQL_ENABLED: true
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guac
      MYSQL_USERNAME: guac
      MYSQL_PASSWORD: guac_pw
      REMOTE_IP_VALVE_ENABLED: true

  web:
    image: nginx
    restart: always
    ports:
      - '8443:443/tcp'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.crt:/etc/nginx/nginx.crt:ro
      - ./nginx.key:/etc/nginx/nginx.key:ro