services:
  guacd:
    image: guacamole/guacd
    restart: unless-stopped
    volumes:
      - ./share_drive:/share
      - ./recordings:/var/lib/guacamole/recordings

  db:
    build: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      PGDATA: /pg_data
    volumes:
      - ./db_data:/pg_data:rw

  guacamole:
    image: guacamole/guacamole
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      WEBAPP_CONTEXT: ROOT
      TOTP_ENABLED: false
      RECORDING_ENABLED: true
      POSTGRESQL_ENABLED: true
      POSTGRESQL_HOSTNAME: db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: some_password
      REMOTE_IP_VALVE_ENABLED: true
    depends_on:
      - guacd
      - db
    volumes:
      - ./share_drive:/share
      - ./recordings:/var/lib/guacamole/recordings

  web:
    build: web
    restart: unless-stopped
    ports:
      - '8443:443/tcp'
    depends_on:
      - guacamole
